name: Example

on:  
  push:
  pull_request:
  workflow_dispatch:


permissions:
  id-token: write
  contents: read


jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
        
# get a token
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


# run a bicep deployment
      - name: run IaC
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create -g azure-oidc -f app-service.bicep
            
